# Default values for rotor.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image: turbinelabs/envoy-simple:0.18.1
imagePullPolicy: Always
