apiVersion: v1
name: Rotor
version: 1
description: An installation of Rotor, a lightweight xDS server for Envoy Proxy
keywords:
  - envoy
  - proxy
  - http2
home: https://docs.turbinelabs.io/advanced/rotor.html
sources:
  - https://github.com/turbinelabs/rotor
maintainers: # (optional)
  - name: Turbine Labs
    email: info@turbinelabs.io
    url: https://turbinelabs.io
icon: https://raw.githubusercontent.com/turbinelabs/rotor/master/rotor.png
appVersion: 0.17.1
